# Generated by Django 3.2.11 on 2022-06-27 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalhealthfeedback',
            name='follow_up',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealthfeedback',
            name='nps_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='mentalhealthfeedback',
            name='session_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
